version: '3.9'

services:
  itranslate_server:
    container_name: itranslate_server
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - itranslate_db
    networks:
      - itranslat_network

  itranslate_db:
    container_name: itranslate_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=itranslate_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - itranslat_network

networks:
  itranslat_network:
    driver: bridge

volumes:
  db-data: