"""Inited project

Revision ID: 6c372cb095dd
Revises: c6acb127bf67
Create Date: 2024-05-20 02:56:27.599077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c372cb095dd'
down_revision: Union[str, None] = 'c6acb127bf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('status', sa.Enum('UNPROCESSED', 'PROCESSING', 'TRANSLATED', 'ERROR', name='translationstatus'), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', name='translationtype'), nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source_language', sa.VARCHAR(length=3), nullable=False),
    sa.Column('source_text', sa.TEXT(), nullable=False),
    sa.Column('target_language', sa.VARCHAR(length=3), nullable=False),
    sa.Column('translated_text', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('translations')
    # ### end Alembic commands ###
